services:
    sqldb: 
        image: mcr.microsoft.com/mssql/server

    # postdb: 
    #     image: mcr.microsoft.com/mssql/server


    # yarpapigateway:
    #     image: ${DOCKER_REGISTRY-}yarpapigateway
    #     build:
    #       context: .
    #       dockerfile: ApiGateways/YarpApiGateway/Dockerfile
    ai.service:
        build:
          context: ./AIService
          dockerfile: Dockerfile
        container_name: ai.service
        ports:
          - "8000:8000"
        restart: always


volumes:
  sqlserver:
  # sqlserver_post:
  

