services:
  sqldb:
    container_name: sqldb
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Hquoan12345678
    ports:
      - "1400:1433"
    volumes:
      - sqlserver:/var/opt/mssql
    restart: on-failure

  messagebroker:
    container_name: messagebroker
    hostname: ecommerce-mq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: on-failure

  auth.api:
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      # - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__DefaultConnection=Server=sqldb;Database=BackToYou_Auth;User Id=sa;Password=Hquoan12345678;Encrypt=False;TrustServerCertificate=True
      - ApiSettings__ConfirmEmailUrl=https://api.backtoyou.io.vn/auth-service/auth/confirm-email
      # - ApiSettings__WebClientUrl=http://localhost:5000
      - ApiSettings__WebClientUrl=https://backtoyou.io.vn
      - ServiceUrls__PaymentAPI=http://paymentapi:8080
    depends_on:
      - sqldb
    ports:
      - "6002:8080"
      # - "6062:8081"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: on-failure

  postapi:
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      # - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__DefaultConnection=Server=sqldb;Database=BackToYou_Post;User Id=sa;Password=Hquoan12345678;Encrypt=False;TrustServerCertificate=True
      - ServiceUrls__AuthAPI=http://auth.api:8080
      - ServiceUrls__PaymentAPI=http://paymentapi:8080
      - MessageBroker__Host=amqp://messagebroker:5672
    depends_on:
      - sqldb
    ports:
      - "6003:8080"
      # - "6063:8081"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: on-failure

  paymentapi:
    environment:
        - TZ=Asia/Ho_Chi_Minh
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_HTTP_PORTS=8080
        # - ASPNETCORE_HTTPS_PORTS=8081
        - ConnectionStrings__DefaultConnection=Server=sqldb;Database=BackToYou_Payment;User Id=sa;Password=Hquoan12345678;Encrypt=False;TrustServerCertificate=True
        - ServiceUrls__AuthAPI=http://auth.api:8080
    depends_on:
        - sqldb
    ports:
        - "6004:8080"
        # - "6064:8081"
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro
    restart: on-failure

  notificationapi:
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      # - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__DefaultConnection=Server=sqldb;Database=BackToYou_Notification;User Id=sa;Password=Hquoan12345678;Encrypt=False;TrustServerCertificate=True
      - MessageBroker__Host=amqp://messagebroker:5672
    depends_on:
        - sqldb
    ports:
      - "6005:8080"
      # - "6065:8081"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: on-failure

  yarpapigateway:
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      # - ASPNETCORE_HTTPS_PORTS=8081
    depends_on:
      - auth.api
      - postapi
      - paymentapi
      - notificationapi
    ports:
      - "6001:8080"
      # - "6061:8081"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: on-failure


