services:
    sqldb: 
        image: mcr.microsoft.com/mssql/server

    messagebroker:
        image: rabbitmq:management

    yarpapigateway:
        image: ${DOCKER_REGISTRY-}yarpapigateway
        build:
          context: .
          dockerfile: ApiGateways/YarpApiGateway/Dockerfile

    auth.api:
        image: ${DOCKER_REGISTRY-}authapi
        build:
            context: .
            dockerfile: Services/Auth/Auth.API/Dockerfile

    postapi:
        image: ${DOCKER_REGISTRY-}postapi
        build:
            context: .
            dockerfile: Services/Post/PostAPI/Dockerfile

    paymentapi:
        image: ${DOCKER_REGISTRY-}paymentapi
        build:
            context: .
            dockerfile: Services/Payment/PaymentAPI/Dockerfile

    notificationapi:
        image: ${DOCKER_REGISTRY-}notificationapi
        build:
          context: .
          dockerfile: Services/Notification/NotificationAPI/Dockerfile

volumes:
  sqlserver:
  # sqlserver_post:

networks:
  api-network:


