services:
  authdb:
    container_name: authdb
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Hquoan12345678
    restart: always
    ports:
      - "1400:1433"
    volumes:
      - sqlserver_auth:/var/opt/mssql
  # postdb:
  #   container_name: postdb
  #   environment:
  #     - ACCEPT_EULA=Y
  #     - SA_PASSWORD=Hquoan12345678
  #   restart: always
  #   ports:
  #     - "1400:1433"
  #   volumes:
  #     - sqlserver_post:/var/opt/mssql
  
  # yarpapigateway:
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_HTTP_PORTS=8080
  #     - ASPNETCORE_HTTPS_PORTS=8081
  #   ports:
  #     - "6001:8080"
  #     - "6061:8081"
  #   volumes:
  #     - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
  #     - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  #     - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  #     - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
